### PR TITLE
fixes #304 by adding clean property.

### LINKED ISSUE #304: Avoid conflicts when starting from clean tests
Sometimes because of error situations there are containers that are not removed and when you reexecute a test, that test fails with next exception:

```
Caused by: com.github.dockerjava.api.ConflictException: Conflict. The name "swapi" is already in use by container ad7867399832. You have to remove (or rename) that container to be able to reuse that name.

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:51)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:32)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:14)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:142)
	at org.arquillian.cube.docker.impl.docker.DockerClientExecutor.createContainer(DockerClientExecutor.java:333)
	at org.arquillian.cube.docker.impl.model.DockerCube.create(DockerCube.java:96)
	... 18 more
```

Maybe we could create a new property called `clean` that by default is false, but if it is true and this exception is thrown, Cube automatically removes the image and reexecute the command.

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

File: docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java [hunk 1]
```diff
@@ -340,6 +341,16 @@ public String createContainer(String name, CubeContainer containerConfiguration)
             } else {
                 throw e;
             }
+        } catch (ConflictException e) {
```
Comment (aslakknutsen) [inline docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java]: Wondering if this logic doesn't fit better in DockerCube.create()

Comment (lordofthejars) [inline docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java]: I thought the same but since for example the NotFoundException is also treated here, I decided to put all these automatic things in the same place.

Comment (aslakknutsen) [inline docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java]: mm, true.
