### PR TITLE
[issue 1397] - Adding support to mount volumes with free string configuration option

### LINKED ISSUE #1397: Docker: `ContainerDsl`, `ContainerDslRule` and `ContainerBuilder` don't support adding volumes with the SELinux labeling configuration option
**Describe the bug**
`ContainerDsl`, `ContainerDslRule` and `ContainerBuilder` provide a `withVolume` method which only accepts the BindMode enumeration to set a volume mount binding options. 
Such implementation does not allow using the `z` or `Z` options to configure SELinux labeling, see https://docs.docker.com/engine/storage/bind-mounts/#options-for---volume and ultimately results in a failure when trying to start a container which expects a volume mounted with such option, as for instance a PostgreSql container. 

**To Reproduce**
1. Inject a `@DockerContainer` which expects a volume to be mounted with the `Z` option, e.g.:
```
@DockerContainer
    Container postgres = Container.withContainerName("postgres")
            .fromImage("quay.io/centos7/postgresql-13-centos7:centos7")
            .withPortBinding("5432->5432")
            .withEnvironment("POSTGRESQL_DATABASE", POSTGRESQL_DATABASE) // creates POSTGRESQL_DATABASE database after 1st start
            .withEnvironment("POSTGRESQL_USER", POSTGRESQL_USER)
            .withEnvironment("POSTGRESQL_PASSWORD", POSTGRESQL_PASSWORD)
            .withVolume(postgresDataDir.getAbsolutePath(), "/var/lib/pgsql/data:Z")
            .withAwaitStrategy(postgresContainerAwaitStrategy())
            .build();
``` 
2. Run the test and see it fail with Arquillian Cube failing at starting the container because of a parsing error of the volume mount which basically turns out to be as follows:
`<host_volume_path>:/var/lib/pgsql/data:Z:rw`

**Expected behavior**
It should be possible to call `.withVolume(postgresDataDir.getAbsolutePath(), "/var/lib/pgsql/data:Z")` without having an additional option - i.e. `rw` - added by default and the container should start.

**Screenshots**
N/A

**Additional context**
This behavior is not aligned with what is done by  [DockerContainerObjectBuilder](https://github.com/arquillian/arquillian-cube/blob/main/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilder.java#L440) which instead is adding the `:Z` option by default when binding volumes.

### PR DESCRIPTION
**Pull request by fabiobrz**
#### Short description of what this resolves:
Changes allow to set a free form bind mount configuration option when creating a docker container so that - for example - `:Z` can be set for container that run on SELinux.

#### Changes proposed in this pull request:

- Adding an overloaded version of `withVolume(String, String, String)` to ContainerBuilder, ContainerDsl and ContainerDslRule to allow setting free form option for volume mounts.

Fixes #1397

### CODE REVIEW

File: docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+        }
+    }
+
+    private static File createPostgresDataDir() throws IOException {
+        // create local data dir for postgres database
+        File postgresDataDir = java.nio.file.Files.createTempDirectory(null).toFile();
+        // This is needed to run on SELinux enabled Docker hosts
+        // otherwise the following error will prevent the container from starting successfully:
+        //   mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
+        java.nio.file.Files.setPosixFilePermissions(Path.of(postgresDataDir.toURI()),
```
Comment (gaol) [inline docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java:60]: Shall we check the OS before calling `setPosixFilePermissions` in case running on Windows ?

File: docker/ftest-docker-containerobject-dsl/src/test/java/org/arquillian/cube/containerobject/dsl/PostgreSqlIT.java [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+            throw new IllegalStateException("Cannot create PostgreSql data dir", e);
+        }
+    }
+
+    @BeforeClass
+    public static void configurePostgresDataDir() throws IOException {
+        // This is needed to run on SELinux enabled Docker hosts
+        // otherwise the following error will prevent the container from starting successfully:
+        //   mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
+        java.nio.file.Files.setPosixFilePermissions(Path.of(POSTGRESQL_HOST_DATA_DIRECTORY.toURI()),
```
Comment (gaol) [inline docker/ftest-docker-containerobject-dsl/src/test/java/org/arquillian/cube/containerobject/dsl/PostgreSqlIT.java:60]: Shall we check the OS before calling `setPosixFilePermissions` in case running on Windows  ?

File: docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+ *     Docker container.
+ *     The data directory is created statically, so that it can be used by the {@link ContainerDslRule} definition later
+ *     in the test lifecycle.
+ *     The {@code Z} bind mode option is passed so that it can be used by SELinux enabled systems, see the related
+ *     <a href="https://docs.docker.com/engine/storage/bind-mounts/#configure-the-selinux-label">Docker documentation</a>,
+ *     otherwise the container would fail to start with the following error:<br>
+ *     {@code mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied}
+ * </p>
+ */
+@Category({ RequiresDocker.class})
```
Comment (gaol) [inline docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java:36]: Shall we add `@RunWith(ArquillianConditionalRunner.class)` to make the `RequiresDocker` work as expected or am I missing something ?

**Review by gaol — COMMENTED** [review]
Overall it looks good to me :+1: 

I have some comments though on the test codes just in case my concerns are valid :)

File: docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java (hunk 3 above)
Comment (fabiobrz) [reply docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java:40]: It is not always needed, as in this case, i.e. when using `@ClassRule` with `ContainerDslRule', see https://arquillian.org/arquillian-cube/#_junit_rule

File: docker/ftest-docker-containerobject-dsl/src/test/java/org/arquillian/cube/containerobject/dsl/PostgreSqlIT.java (hunk 2 above)
Comment (fabiobrz) [reply docker/ftest-docker-containerobject-dsl/src/test/java/org/arquillian/cube/containerobject/dsl/PostgreSqlIT.java]: Thanks, fixed.

File: docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java (hunk 1 above)
Comment (fabiobrz) [reply docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java]: Thanks, fixed.

**Comment by fabiobrz** [comment]
> Overall it looks good to me 👍
> 
> I have some comments though on the test codes just in case my concerns are valid :)

Thanks for your review @gaol, I've addressed your comments. Feel free to let me know if there's anything else you'd wish to discuss.

File: docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java (hunk 3 above)
Comment (gaol) [reply docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java:38]: Ah, yes. that is the thing I am missing :) thank you .
