### PR TITLE
fix(#851): Unify names of annotations to be more consistent with plural

### LINKED ISSUE #851: Use `@Repeatable` annotations in OpenShift annotations
##### Issue Overview

Some annotations such as `@Templates`, `@OpenShiftResources, ... does not using `@Repeatable` approach.

##### Expected Behaviour

Implement annotations with `@Repeatable`

##### Current Behaviour

Uses old way (prior to Java8)

### PR DESCRIPTION
**Pull request by lordofthejars**
#### Short description of what this resolves:

Unify names of annotations to its plural instead of `wrapper` and use `@Repeatable` in these classes.

Fixes #851

### CODE REVIEW

**Comment by lordofthejars** [comment]
@Ladicek you can review the names and if you agree I'll merge it.

File: openshift/api/src/main/java/org/arquillian/cube/openshift/api/RoleBindings.java [hunk 1]
```diff
@@ -24,6 +24,7 @@
 package org.arquillian.cube.openshift.api;
 
 import java.lang.annotation.ElementType;
+import java.lang.annotation.Repeatable;
```
Comment (Ladicek) [inline openshift/api/src/main/java/org/arquillian/cube/openshift/api/RoleBindings.java]: Unused import?

File: openshift/api/src/main/java/org/arquillian/cube/openshift/api/AddRoleToServiceAccounts.java [hunk 2]
```diff
@@ -33,6 +33,6 @@
  */
 @Retention(RetentionPolicy.RUNTIME)
 @Target(ElementType.TYPE)
-public @interface AddRoleToServiceAccountWrapper {
+public @interface AddRoleToServiceAccounts {
```
Comment (Ladicek) [inline openshift/api/src/main/java/org/arquillian/cube/openshift/api/AddRoleToServiceAccounts.java]: Hmm I see why they called it a `Wrapper` instead of using simple plural. Maybe call it `AddRolesToServiceAccounts`?

Comment (lordofthejars) [reply openshift/api/src/main/java/org/arquillian/cube/openshift/api/AddRoleToServiceAccounts.java]: so plural roles and plural accounts

Comment (Ladicek) [reply openshift/api/src/main/java/org/arquillian/cube/openshift/api/AddRoleToServiceAccounts.java]: Right.

**Comment by lordofthejars** [comment]
Done
