### PR TITLE
Fix SessionManager in order to use a supported way to determine whether the the client is a k8s or OpenShift one

### LINKED ISSUE #1360: SessionManager::start should replace the deprecated call to `client.isAdaptable()` which has caused some problems when making changes to support more recent JDKs
SSIA

### PR DESCRIPTION
**Pull request by fabiobrz**
#### Short description of what this resolves:
SessionManager is using a deprecated call to `isAdaptable`. This can lead to some classpath issues with Fabtric8 Kubernetes Client adapters, so this PR is proposing to replace the call with the non deprecated `supports()` method

#### Changes proposed in this pull request:

- SessionManager::start 

Resolves #1360

### CODE REVIEW

**Comment by fabiobrz** [comment]
Hi @rhusar, JFYI this is ready for review now.

**Review by rhusar — CHANGES_REQUESTED** [review]
There is a lot more usage of this deprecated API, this should be fixed across the codebase.

```
kubernetes/istio/istio/src/main/java/org/arquillian/cube/istio/impl/IstioClientAdapter.java:    public <C extends Client> Boolean isAdaptable(Class<C> type) {
kubernetes/istio/istio/src/main/java/org/arquillian/cube/istio/impl/IstioClientAdapter.java:        return unwrap().isAdaptable(type);
kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/namespace/DefaultNamespaceService.java:            if (client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftClientCreator.java:        if (kubernetesClient != null && kubernetesClient.isAdaptable(io.fabric8.openshift.client.OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/external/OpenshiftClientResourceProvider.java:        } else if (!client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/internal/OpenshiftClientResourceProvider.java:        } else if (!client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/install/OpenshiftResourceInstaller.java:            if (!client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/locator/OpenshiftKubernetesResourceLocator.java:        if (!client.get().isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/locator/OpenshiftKubernetesResourceLocator.java:        if (!client.get().isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java:            if (client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java:            if (client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java:            if (client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java:            if (client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java:            if (client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/Openshift4Requirement.java:            } else if (!client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/OpenshiftOlmRequirement.java:                if (!client.isAdaptable(OpenShiftClient.class)) {
openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/OpenshiftRequirement.java:            } else if (!client.isAdaptable(OpenShiftClient.class)) {
```

**Comment by fabiobrz** [comment]
Hi @rhusar - this should be ready now, could you have a look? :pray:

File: kubernetes/istio/istio/src/main/java/org/arquillian/cube/istio/impl/IstioClientAdapter.java [hunk 1]
```diff
@@ -59,6 +59,7 @@ public V1alpha3APIGroupDSL v1alpha3() {
         return unwrap().v1alpha3();
     }
 
+    @Deprecated
```
Comment (rhusar) [inline kubernetes/istio/istio/src/main/java/org/arquillian/cube/istio/impl/IstioClientAdapter.java:62]: Nitpick but for future reference, always add Javadoc with `@deprecated` explanation what to use instead.

**Review by rhusar — APPROVED** [review]
OK I was able to locate the code recommentation in upstream repo, all looks good now, with rest of the feedback addressed (ec48180b8b3a97c974bfd2bee51a093cd4cb7b95 in `fabric8io/kubernetes-client`)
